Factory/Models/EngMachine.cs
namespace Factory.Models;

public class EngMachine
{
  public int EngMachineId { get; set; }
  public int EngineerId { get; set; }
  public Engineer Engineer { get; set; }
  public int MachineId { get; set; }
  public Machine Machine { get; set; }
}

Factory/Models/Engineers.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models;

public class Engineer
{
  public int EngineerId { get; set; }
  [Required(ErrorMessage="Please Enter a Name")]
  public string Name { get; set; }
  public List<EngMachine> JoinEntities { get; }
}

Factory/Models/Machines.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models;

public class Machine
{
  public int MachineId { get; set; }
  [Required(ErrorMessage="Please Enter a Name")]
  public string Name { get; set; }
  public List<EngMachine> JoinEntities { get; }
}

Factory/Models/SSFactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class SSFactoryContext : DbContext
  {
    public DbSet<Machine> Machines { get; set; }
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<EngMachine> EngMachines { get; set; }
    public SSFactoryContext(DbContextOptions options) : base(options) { }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers;

  public class EngineersController : Controller
  {
    private readonly SSFactoryContext _db;
    public EngineersController(SSFactoryContext db)
    {
      _db = db;
    }
  
    public ActionResult Index()
    {
      List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      // ViewBag.machineList = _db.Machines.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
        if (!ModelState.IsValid)
        {
          return View(engineer);
        }
        else
        {
        _db.Engineers.Add(engineer);
        _db.SaveChanges();
        return RedirectToAction("Index");
        }
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
  #nullable enable
      EngMachine? joinEntity = _db.EngMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
  #nullable disable 
      if (joinEntity == null && machineId !=0)
      {
        _db.EngMachines.Add(new EngMachine() { MachineId = machineId, EngineerId = engineer.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
                                          .Include(eng => eng.JoinEntities)
                                          .ThenInclude(join => join.Machine)
                                          .FirstOrDefault(eng => eng.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(eng => eng.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngMachine joinEntry = _db.EngMachines.FirstOrDefault(entry => entry.EngMachineId == joinId);
      _db.EngMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers;

  public class HomeController : Controller
  {
    private readonly SSFactoryContext _db;

    public HomeController(SSFactoryContext db)
    {
      _db = db;
    }

    [HttpGet("/")]
    public ActionResult Index()
    {
      List<Engineer> engineers = _db.Engineers.ToList();
      List<Machine> machines = _db.Machines.ToList();
      ViewBag.engineers = engineers;
      ViewBag.machines = machines;
      return View();
    }
  }

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers;

  public class MachinesController : Controller
  {
    private readonly SSFactoryContext _db;
    public MachinesController(SSFactoryContext db)
    {
      _db = db;
    }
  
    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
  #nullable enable
      EngMachine? joinEntity = _db.EngMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
  #nullable disable 
      if (joinEntity == null && engineerId !=0)
      {
        _db.EngMachines.Add(new EngMachine() { EngineerId = engineerId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
                                          .Include(eng => eng.JoinEntities)
                                          .ThenInclude(join => join.Engineer)
                                          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

        [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngMachine joinEntry = _db.EngMachines.FirstOrDefault(entry => entry.EngMachineId == joinId);
      _db.EngMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add a Machine</h2>

<h2>Add a machine, that @Html.DisplayFor(model => model.Name) is authorized to service.</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Add An Engineer</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger"})</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Save" />
}

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Delete</h2>

<h4>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  <input type="submit" value="Yes, delete" />
}

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Engineer

<h2>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h2>

<h4>Machines this engineer is authorized to service:</h4>

@if (Model.JoinEntities.Count == 0)
{
  <p>No machines added yet</p>
}
else
{
  <h4>Machines:</h4>
  <ol>
  @foreach (EngMachine join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{join.Machine.Name}", "Details", "Machines", new { id = join.Machine.MachineId})

        @using (Html.BeginForm("DeleteJoin", "Engineers"))
        {
          @Html.Hidden("joinId", @join.EngMachineId)
          <input type="submit" value="Remove machine from Engineer" />
        }
      </li>
    }
  </ol>
}


<p>@Html.ActionLink("Add a machine", "AddMachine", new { id = Model.EngineerId})</p>
<p>@Html.ActionLink("Edit", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save Changes" />
}

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h2>Engineers</h2>

@if (Model.Count == 0)
{
  <p>No Engineers Added Yet</p>
}

@foreach (Engineer engineer in Model)
{
  <p>@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId})</p>
}

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Welcome to the Dr. SillyStringz Factory!</h1>

<hr>

<h4>Engineers</h4>
@if (ViewBag.engineers.Count == 0)
{
  <p>No engineers have been added</p>
}
<ol>
  @foreach (Engineer engineer in ViewBag.engineers)
  {
    <li>@Html.ActionLink(@engineer.Name, "Details", "Engineers", new { id = @engineer.EngineerId})</li>
  }
</ol>

<h4>Machines</h4>
@if (ViewBag.Machines.Count == 0 )
{
  <p>No machines added yet</p>
}
<ol>
  @foreach (Machine machine in ViewBag.machines)
  {
    <li>@Html.ActionLink(@machine.Name, "Details", "Machines", new { id = @machine.MachineId})</li>
  }
</ol>

Factory/Views/Machines/AddEngineer.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Enmgineer</h2>

<h2>Add an engineer who is authorized to service this machine.</h2>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.Label("Select Engineer")
  @Html.DropDownList("EngineerId")

  <input type="submit" value="Save" />
}

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add A Machine</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger"})</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Save" />
}

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Delete</h2>

<h4>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  <input type="submit" value="Yes, delete" />
}

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models
@model Factory.Models.Machine

<h2>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h2>

<h4>Engineers who are authorized to service this machine: 

@if (Model.JoinEntities.Count == 0)
{
  <p>No engineers added yet</p>
}
else
{
  <h4>Engineers:</h4>
  <ol>
  @foreach (EngMachine join in Model.JoinEntities)
    {
      <li>@Html.ActionLink($"{join.Engineer.Name}", "Details", "Engineers", new { id = join.Engineer.EngineerId})

        @using (Html.BeginForm("DeleteJoin", "Engineers"))
        {
          @Html.Hidden("joinId", @join.EngMachineId)
          <input type="submit" value="Remove machine from Engineer" />
        }
      </li>
    }
  </ol>
}


<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId})</p>
<p>@Html.ActionLink("Edit", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)
  
  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save Changes" />
}

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models

<h2>Machines</h2>

@if (Model.Count == 0)
{
  <p>No Machines Added Yet</p>
}

@foreach (Machine machine in Model)
{
  <p>@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId})</p>
}

Factory/Views/Shared/Header.cshtml
<div class="header">
  <h1>Dr. SillyStringz</h1>
</div>

Factory/Views/Shared/NavBar.cshtml
<div class="navbar">
  <p>@Html.ActionLink("Home","Index","Home")</p>
  <p>@Html.ActionLink("Engineers", "Index", "Engineers")</p>
  <p>@Html.ActionLink("Add Engineer", "Create", "Engineers")</p>
  <p>@Html.ActionLink("Machines", "Index", "Machines")</p>
  <p>@Html.ActionLink("Add Machine", "Create", "Machines")</p>
</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Dr. SillyStringz Factory</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
</head>

<body>
  @await Html.PartialAsync("Header")
  @await Html.PartialAsync("NavBar")
  @RenderBody()
  </div>
</body>

</html>